"""
Django settings for Stephanos_Estetic project.
Generated by 'django-admin startproject' (Django 5.2.6).
"""

# ──────────────────────────────────────────────────────────────────────────────
# Imports & Paths
# ──────────────────────────────────────────────────────────────────────────────
from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent  # carpeta raíz (donde está manage.py)

# Cargar variables de entorno desde .env en la raíz del proyecto
load_dotenv(BASE_DIR / ".env")

# ──────────────────────────────────────────────────────────────────────────────
# Core / Seguridad
# ──────────────────────────────────────────────────────────────────────────────
SECRET_KEY = "django-insecure-a*ei31nk+g*tw@=*i588z2%h(w)1@e*a%$0ebbrkn$#0l^q$t%"  # cambia en prod
DEBUG = True
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# ──────────────────────────────────────────────────────────────────────────────
# Apps
# ──────────────────────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Terceros
    "rest_framework",
    "corsheaders",
    "import_export",

    # Proyecto
    "SE_donations",
    "SE_sales",
    "SE_services",
    "SE_contact",
    "SE_payments",
    "SE_users",
]

# ──────────────────────────────────────────────────────────────────────────────
# Middleware
# ──────────────────────────────────────────────────────────────────────────────
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS debe ir arriba de CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Stephanos_Estetic.urls"
WSGI_APPLICATION = "Stephanos_Estetic.wsgi.application"

# ──────────────────────────────────────────────────────────────────────────────
# CORS / CSRF (SPA en Vite)
# ──────────────────────────────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True  # permite enviar cookies (csrftoken / session)

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Cookies en desarrollo (ajusta para producción con HTTPS)
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False  # debe ser False si lees csrftoken desde JS

# Mantén los slashes de Django
APPEND_SLASH = True

# ──────────────────────────────────────────────────────────────────────────────
# Templates
# ──────────────────────────────────────────────────────────────────────────────
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # si usas templates del admin/auth
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ──────────────────────────────────────────────────────────────────────────────
# Base de datos
# ──────────────────────────────────────────────────────────────────────────────
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ──────────────────────────────────────────────────────────────────────────────
# Passwords
# ──────────────────────────────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ──────────────────────────────────────────────────────────────────────────────
# I18N / TZ
# ──────────────────────────────────────────────────────────────────────────────
LANGUAGE_CODE = "en-us"               # puedes cambiar a "es-cl" si quieres
TIME_ZONE = "America/Santiago"
USE_I18N = True
USE_TZ = True

# ──────────────────────────────────────────────────────────────────────────────
# Static
# ──────────────────────────────────────────────────────────────────────────────
STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ──────────────────────────────────────────────────────────────────────────────
# REST Framework (ajusta permisos y throttles según tus endpoints)
# ──────────────────────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/min",
        "user": "120/min",
        "contact_form": "5/hour",
    },
}

# ──────────────────────────────────────────────────────────────────────────────
# Auth redirects
# ──────────────────────────────────────────────────────────────────────────────
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# ──────────────────────────────────────────────────────────────────────────────
# Constantes del proyecto
# ──────────────────────────────────────────────────────────────────────────────
FRONTEND_URL = "http://localhost:5173"

WEBPAY_ENV = os.getenv("WEBPAY_ENV", "TEST")
WEBPAY_COMMERCE_CODE = os.getenv("WEBPAY_COMMERCE_CODE", "")
WEBPAY_API_KEY = os.getenv("WEBPAY_API_KEY", "")
WEBPAY_RETURN_URL = "http://localhost:8000/api/payments/commit"

# Google OAuth (backend). Leemos cualquiera de los dos nombres por comodidad.
GOOGLE_CLIENT_ID = (
    os.getenv("GOOGLE_OAUTH_CLIENT_ID")
    or os.getenv("GOOGLE_CLIENT_ID")
    or ""
)
